all: MiniMaxOpening MiniMaxGame aivsai

MiniMaxOpening: ../headers/* MiniMaxOpening.cpp
	g++ -o MiniMaxOpening MiniMaxOpening.cpp

MiniMaxGame: ../headers/* MiniMaxGame.cpp
	g++ -o MiniMaxGame MiniMaxGame.cpp