all: MiniMaxOpening MiniMaxGame aivsai

MiniMaxOpening: ../headers/* MiniMaxOpening.cpp
	g++ -o MiniMaxOpening MiniMaxOpening.cpp

MiniMaxGame: ../headers/* MiniMaxGame.cpp
	g++ -o MiniMaxGame MiniMaxGame.cpp

# aivsai: MiniMaxGame.exe MiniMaxOpening.exe 
# 	g++ -o aivsai MiniMaxGame.exe MiniMaxOpening.exe 